---
title: "BDA - Project"
author: "Anonymous"
output:
  pdf_document:
    toc: yes
    toc_depth: 1
  word_document:
    toc: yes
    toc_depth: '1'
urlcolor: blue
---

```{r setup, include=FALSE, warning=FALSE}
# This chunk sets echo = TRUE as default, that is print all code.
# knitr::opts_chunk$set can be used to set other notebook generation options, too.
# include=FALSE inside curly brackets makes this block not be included in the pdf.
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

## The motivation





## The Problem




## The main modeling idea 




##  Some illustrative figure



# Description of the data and the analysis problem. Provide information where the data was obtained, and if it has been previously used in some online case study and how your analysis differs from the existing analyses.


# Description of at least two models, for example:non hierarchical and hierarchical


# Informative or weakly informative priors, and justification of their choices.

# Stan, rstanarm or brms code.

# How to the Stan model was run, that is, what options were used. This is also more clear as combination of textual explanation and the actual code line.

# Convergence diagnostics (Rˆ, ESS, divergences) and what was done if the convergence was not good with the first try.


# Posterior predictive checks and what was done to improve the model.

# Model comparison (e.g. with LOO-CV).

# Predictive performance assessment if applicable (e.g. classification accuracy) and evaluation of practical usefulness of the accuracy. If not applicable, then explanation why in this case the predictive performance is not applicable.



# Sensitivity analysis with respect to prior choices (i.e. checking whether the result changes a lot if prior is changed)


# Discussion of issues and potential improvements.


# Conclusion what was learned from the data analysis.



# Self-reflection of what the group learned while making the project.

